import type { Diagram } from "./schema";

export const SAMPLE_DIAGRAM: Diagram = {
  title: "Proceso de solicitud y aprobación",
  subtitle: "Ejemplo reconstruido · swimlanes interactivas",
  type: "swimlane",
  direction: "LR",
  groups: [
    {
      id: "g1",
      label: "Solicitante",
      description: "Persona o área que inicia el trámite",
    },
    {
      id: "g2",
      label: "Ventanilla",
      description: "Recepción, radicación y checklist",
    },
    {
      id: "g3",
      label: "Área técnica",
      description: "Evaluación de fondo y concepto",
    },
    {
      id: "g4",
      label: "Dirección",
      description: "Decisión final y cierre",
    },
  ],
  nodes: [
    {
      id: "n1",
      label: "Preparar solicitud",
      description: "Reúne formulario, anexos y soportes.",
      kind: "start",
      groupId: "g1",
    },
    {
      id: "n2",
      label: "Enviar expediente",
      description: "Carga o entrega física del paquete completo.",
      kind: "process",
      groupId: "g1",
    },
    {
      id: "n3",
      label: "Radicar y verificar",
      description: "Asigna número de radicado y revisa requisitos mínimos.",
      kind: "process",
      groupId: "g2",
    },
    {
      id: "n4",
      label: "¿Está completo?",
      description: "Checklist de forma: identidad, anexos, firmas.",
      kind: "decision",
      groupId: "g2",
    },
    {
      id: "n5",
      label: "Devolver con observaciones",
      description: "Lista concreta de faltantes y plazo de subsanación.",
      kind: "io",
      groupId: "g2",
      badge: "NO",
    },
    {
      id: "n6",
      label: "Asignar analista",
      description: "Turno al especialista según tipo de solicitud.",
      kind: "process",
      groupId: "g2",
      badge: "SÍ",
    },
    {
      id: "n7",
      label: "Evaluar de fondo",
      description: "Cruce normativo, viabilidad y riesgos.",
      kind: "process",
      groupId: "g3",
    },
    {
      id: "n8",
      label: "¿Es viable?",
      description: "Concepto técnico favorable o no.",
      kind: "decision",
      groupId: "g3",
    },
    {
      id: "n9",
      label: "Informe de no viabilidad",
      description: "Fundamento y alternativas para el solicitante.",
      kind: "document",
      groupId: "g3",
      badge: "NO",
    },
    {
      id: "n10",
      label: "Concepto técnico",
      description: "Memorando con hallazgos y recomendación.",
      kind: "document",
      groupId: "g3",
      badge: "SÍ",
    },
    {
      id: "n11",
      label: "Revisar y decidir",
      description: "Dirección firma aprobación, ajuste o rechazo.",
      kind: "process",
      groupId: "g4",
    },
    {
      id: "n12",
      label: "Notificar resolución",
      description: "Comunicación oficial al solicitante y archivo.",
      kind: "end",
      groupId: "g4",
    },
    {
      id: "n13",
      label: "Subsanar y reenviar",
      description: "El solicitante corrige y vuelve a ventanilla.",
      kind: "process",
      groupId: "g1",
    },
  ],
  edges: [
    { id: "e1", source: "n1", target: "n2" },
    { id: "e2", source: "n2", target: "n3" },
    { id: "e3", source: "n3", target: "n4" },
    { id: "e4", source: "n4", target: "n5", label: "Incompleto", kind: "warning" },
    { id: "e5", source: "n5", target: "n13" },
    { id: "e6", source: "n13", target: "n3", kind: "dashed" },
    { id: "e7", source: "n4", target: "n6", label: "Completo", kind: "success" },
    { id: "e8", source: "n6", target: "n7" },
    { id: "e9", source: "n7", target: "n8" },
    { id: "e10", source: "n8", target: "n9", label: "No viable", kind: "warning" },
    { id: "e11", source: "n9", target: "n12" },
    { id: "e12", source: "n8", target: "n10", label: "Viable", kind: "success" },
    { id: "e13", source: "n10", target: "n11" },
    { id: "e14", source: "n11", target: "n12" },
  ],
  notes: [
    "Los plazos de subsanación y de concepto técnico se definen en el instructivo interno.",
    "Cada recuadro se puede seleccionar para ver el detalle.",
  ],
};
